<?php

/**
 * (c) Spryker Systems GmbH copyright protected
 */

namespace SprykerFeature\Shared\Application;

use SprykerFeature\Shared\Library\ConfigInterface;

interface ApplicationConfig extends ConfigInterface
{

    const ALLOW_INTEGRATION_CHECKS = 'ALLOW_INTEGRATION_CHECKS';
    const COUCHBASE_BUCKET_PREFIX = 'COUCHBASE_BUCKET_PREFIX';
    const DISPLAY_ERRORS = 'DISPLAY_ERRORS';

    const ENABLE_APPLICATION_DEBUG = 'ENABLE_APPLICATION_DEBUG';
    const ENABLE_WEB_PROFILER = 'ENABLE_WEB_PROFILER';
    const NAVIGATION_CACHE_ENABLED = 'navigation cache enabled';
    const SET_REPEAT_DATA = 'SET_REPEAT_DATA';
    const SHOW_SYMFONY_TOOLBAR = 'SHOW_SYMFONY_TOOLBAR';
    const STORE_PREFIX = 'STORE_PREFIX';
    // see http://twig.sensiolabs.org/doc/api.html#environment-options
    const YVES_TWIG_OPTIONS = 'YVES_TWIG_OPTIONS';
    const ZED_TWIG_OPTIONS = 'ZED_TWIG_OPTIONS';


    const YVES_THEME = 'YVES_THEME';
    const YVES_TRUSTED_PROXIES = 'YVES_TRUSTED_PROXIES';
    const YVES_SSL_ENABLED = 'YVES_SSL_ENABLED';
    const YVES_COMPLETE_SSL_ENABLED = 'YVES_COMPLETE_SSL_ENABLED';
    const YVES_SSL_EXCLUDED = 'YVES_SSL_EXCLUDED';
    const YVES_SESSION_SAVE_HANDLER = 'YVES_SESSION_SAVE_HANDLER';
    const YVES_SESSION_NAME = 'YVES_SESSION_NAME';
    const YVES_SESSION_COOKIE_DOMAIN = 'YVES_SESSION_COOKIE_DOMAIN';
    const YVES_ERROR_PAGE = 'YVES_ERROR_PAGE';
    const YVES_SHOW_EXCEPTION_STACK_TRACE = 'YVES_SHOW_EXCEPTION_STACK_TRACE';

    const TRANSFER_USERNAME = 'TRANSFER_USERNAME';
    const TRANSFER_PASSWORD = 'TRANSFER_PASSWORD';
    const TRANSFER_SSL = 'TRANSFER_SSL';
    const TRANSFER_DEBUG_SESSION_FORWARD_ENABLED = 'TRANSFER_DEBUG_SESSION_FORWARD_ENABLED';
    const TRANSFER_DEBUG_SESSION_NAME = 'TRANSFER_DEBUG_SESSION_NAME';

    const YVES_AUTH_SETTINGS = 'YVES_AUTH_SETTINGS';

}
