<?php  //[STAMP] ec3a75aca11cbdf421d3f53e9d7dbed8
namespace ZedRequest\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use ZedRequest\Codeception\Module\CodeHelper;

trait YvesGuyActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
