build:
    image: default-jammy
    environment:
        php: '8.3'
        node: 'v18.13'

    nodes:
        analysis:
            requires:
                - branch: /^master$|^(bugfix|hotfix|beta)\/.+|^feature\/[a-z]+-\d+\/(master|dev)-.+|^feature\/[a-z]+-\d+\/[a-z]+-\d+\/(master|dev)-.+/
            tests:
                override:
                    - php-scrutinizer-run

filter:
    excluded_paths:
        - Bundles/Propel/src/Spryker/Zed/Propel/Business/Builder/*
        - Bundles/PropelOrm/src/Spryker/Zed/PropelOrm/Business/Polyfill/*
        - Bundles/Security/src/Spryker/Yves/Security/Plugin/Application/*
        - Bundles/Security/src/Spryker/Zed/Security/Communication/Plugin/Application/*
        - Bundles/*/src/Spryker/Zed/*/*/*Factory.php
        - Bundles/*/src/Spryker/Client/*/*Factory.php
        - Bundles/*/src/Spryker/*/*/*DependencyProvider.php
        - Bundles/Transfer/tests/_data/test_files/*
        - Bundles/*/tests/SprykerTest/*/*/_support/*Tester.php
        - Bundles/Development/*
        - Features/*/src/SprykerFeature/Zed/*/*/*Factory.php
        - Features/*/src/SprykerFeature/*/*/*DependencyProvider.php
        - Features/*/src/SprykerFeature/*/*/*Repository.php
        - Features/*/src/SprykerFeature/*/*/*EntityManager.php
        - Features/*/src/SprykerFeature/*/*/*Config.php
        - Features/*/src/SprykerFeature/Yves/*/*Factory.php
        - Features/*/tests/SprykerFeatureTest/Shared/*/*/*/*Helper.php
        - Features/*/tests/SprykerFeatureTest/*/*/_support/*Tester.php

build_failure_conditions:
    - 'project.metric("scrutinizer.quality", < 9.80)'
