<?php  //[STAMP] 437669496facec7136c928f358b6f7a9
namespace SprykerTest\Zed\MerchantCategorySearch\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait MerchantCategorySearchCommunicationTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
