<?php

/**
 * (c) Spryker Systems GmbH copyright protected
 */

namespace SprykerFeature\Shared\Customer;

use SprykerFeature\Shared\Library\ConfigInterface;

interface CustomerConfig extends ConfigInterface
{

    const CUSTOMER_ANONYMOUS_PATTERN = 'CUSTOMER_ANONYMOUS_PATTERN';
    const CUSTOMER_SECURED_PATTERN = 'CUSTOMER_SECURED_PATTERN';
    const SHOP_MAIL_FROM_EMAIL_NAME = 'SHOP_MAIL_FROM_EMAIL_NAME';
    const SHOP_MAIL_FROM_EMAIL_ADDRESS = 'SHOP_MAIL_FROM_EMAIL_ADDRESS';
    const SHOP_MAIL_REGISTRATION_TOKEN = 'SHOP_MAIL_REGISTRATION_TOKEN';
    const SHOP_MAIL_REGISTRATION_SUBJECT = 'SHOP_MAIL_REGISTRATION_SUBJECT';
    const SHOP_MAIL_PASSWORD_RESTORE_TOKEN = 'PASSWORD_RESTORE_TOKEN';
    const SHOP_MAIL_PASSWORD_RESTORE_SUBJECT = 'PASSWORD_RESTORE_SUBJECT';
    const SHOP_MAIL_PASSWORD_RESTORED_CONFIRMATION_TOKEN = 'PASSWORD_RESTORED_CONFIRMATION_TOKEN';
    const SHOP_MAIL_PASSWORD_RESTORED_CONFIRMATION_SUBJECT = 'PASSWORD_RESTORED_CONFIRMATION_SUBJECT';

}
