<?php

/**
 * (c) Spryker Systems GmbH copyright protected
 */

namespace SprykerFeature\Shared\Payolution;

use SprykerFeature\Shared\Library\ConfigInterface;

interface PayolutionConfigConstants extends ConfigInterface
{

    const GATEWAY_URL = 'PAYOLUTION_GATEWAY_URL';
    const TRANSACTION_MODE = 'PAYOLUTION_TRANSACTION_MODE';
    const SECURITY_SENDER = 'PAYOLUTION_SECURITY_SENDER';
    const USER_LOGIN = 'PAYOLUTION_USER_LOGIN';
    const USER_PASSWORD = 'PAYOLUTION_USER_PASSWORD';
    const TRANSACTION_CHANNEL_INVOICE = 'PAYOLUTION_CHANNEL_INVOICE';
    const TRANSACTION_CHANNEL_INSTALLMENT = 'PAYOLUTION_CHANNEL_INSTALLMENT';
    const TRANSACTION_CHANNEL_SYNC = 'PAYOLUTION_CHANNEL_SYNC';
    const TRANSACTION_CHANNEL_PRE_CHECK = 'PAYOLUTION_CHANNEL_PRE_CHECK_ID';
    const DEFAULT_TIMEOUT = 'DEFAULT_TIMEOUT';

    const MIN_ORDER_GRAND_TOTAL_INVOICE = 'PAYOLUTION_MIN_ORDER_GRAND_TOTAL_INVOICE';
    const MAX_ORDER_GRAND_TOTAL_INVOICE = 'PAYOLUTION_MAX_ORDER_GRAND_TOTAL_INVOICE';
    const MIN_ORDER_GRAND_TOTAL_INSTALLMENT = 'PAYOLUTION_MIN_ORDER_GRAND_TOTAL_INSTALLMENT';
    const MAX_ORDER_GRAND_TOTAL_INSTALLMENT = 'PAYOLUTION_MAX_ORDER_GRAND_TOTAL_INSTALLMENT';

    const ANALYSIS_CRITERIA = 'analysis_criteria';

    const EMAIL_TEMPLATE_NAME = 'PAYOLUTION_EMAIL_TEMPLATE_NAME';
    const EMAIL_FROM_NAME = 'PAYOLUTION_EMAIL_FROM_NAME';
    const EMAIL_FROM_ADDRESS = 'PAYOLUTION_EMAIL_FROM_ADDRESS';
    const EMAIL_SUBJECT = 'EMAIL_SUBJECT';

}
