<?php  //[STAMP] ec3a75aca11cbdf421d3f53e9d7dbed8
namespace Kernel\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Kernel\Codeception\Module\CodeHelper;

trait NoGuyActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
