<?php


namespace Spryker\Shared\Synchronization;

interface SynchronizationConstants
{
    public const IS_BULK_MODE_ENABLED = 'SYNCHRONIZATION:IS_BULK_MODE_ENABLED';
    public const DEFAULT_SYNC_STORAGE_QUEUE_MESSAGE_CHUNK_SIZE = 'SYNCHRONIZATION:DEFAULT_SYNC_STORAGE_QUEUE_MESSAGE_CHUNK_SIZE';
    public const DEFAULT_SYNC_SEARCH_QUEUE_MESSAGE_CHUNK_SIZE = 'SYNCHRONIZATION:DEFAULT_SYNC_SEARCH_QUEUE_MESSAGE_CHUNK_SIZE';
    public const EXPORT_MESSAGE_CHUNK_SIZE = 'SYNCHRONIZATION:EXPORT_MESSAGE_CHUNK_SIZE';
}
