#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use ProjectA\OpenStack\Loadbalancer\ListCommand;
use ProjectA\OpenStack\Loadbalancer\UpdateNodeCommand;
use Symfony\Component\Console\Application;

$application = new Application('clc', '@package_version');
$application->add(new ListCommand(null, $application));
$application->add(new UpdateNodeCommand(null, $application));
$application->run();
