<table class="table table-striped table-bordered table-xs">
  <tbody>
    <tr class="row-m">
        <th><?php echo __('Order Type') ?>:
        <td><?php echo $this->order->getIsTest() ? __('TEST') : __('REAL') ?>
    <tr class="row-m">
        <th><?php echo __('Created') ?>:
        <td><?php echo $this->order->getCreatedAt() ?>
    <tr class="row-m">
        <th><?php echo __('Used Coupons') ?>:
        <td>
            <?php $codes = []; ?>
            <?php foreach ($this->order->getCodeUsages() as $codeUsage) : ?>
                <?php $codes[] = $codeUsage->getCode()->getCode(); ?>
            <?php endforeach; ?>
            <?php echo implode(',', $codes); ?>

    <tr class="toggleable">
        <th><?php echo __('Order Number') ?>:
        <td><?php echo $this->order->getIncrementId() ?>
    <tr class="toggleable">
        <th><?php echo __('Order ID') ?>:
        <td><?php echo $this->order->getPrimaryKey() ?>
</table>
