<?php $options = $this->item->getOptions(); ?>
<?php $expenses = $this->item->getExpenses(); ?>
<?php $rowSpan = 1 + count($options) + count($expenses); ?>

<style>
    .currency {text-align:right;}
    .fixed-amount-width-s {width:50px;}
    .fixed-amount-width-m {width:70px;}
    .fixed-amount-width-l {width:90px;}
</style>

<table class="table table-xs table-striped table-bordered table-nested">
    <thead>
        <tr>
            <th><?= __('Product') ?>
            <th><?= __('Gross Price') ?>
            <th><?= __('Discount') ?>
            <th><?= __('Price To Pay') ?>
    <tbody>
        <tr>
            <td>
                <div class="clearfix">
                    <span class="pull-left">
                        <?= $this->item->getName() ?>
                    </span>
                    <span class="pull-right">
                        <a href="/catalog/product/detail-<?= strtolower($this->product->getVariety()) ?>/id-catalog-product/<?= $this->product->getIdCatalogProduct() ?>">
                            <?= $this->item->getSku() ?>
                        </a>
                         / (#<?= $this->item->getPrimaryKey() ?>)
                    </span>
                </div>
                <?= $this->partial('Partials/product-attributes.phtml', array('product' => $this->product)); ?>
            <td class="currency fixed-amount-width-l" style="width:80px;text-align:right;">
                <?= $this->formatPrice($this->item->getGrossPrice()) ?>
            <td class="currency fixed-amount-width-s">
                <?php
                $discountAmount = 0;
                foreach ($this->item->getDiscounts() as $discount) {
                    $discountAmount += $discount->getAmount();
                }
                echo $this->formatPrice($discountAmount);
                ?>
            <td rowspan="<?= $rowSpan ?>" class="currency fixed-amount-width-l">
                <b><?= $this->formatPrice($this->item->getPriceToPay()) ?></b>

        <!-- EXPENSES -->
        <?php foreach($expenses as $expense) : ?>
            <tr>
                <td>+ <?= $expense->getName() ?> <?= $expense->getType() ?> (item-expense)
                <td class="currency"><?= $this->formatPrice($expense->getGrossPrice()) ?>
                <td class="currency">
                    <?php
                        $discountAmount = 0;
                        foreach ($expense->getDiscounts() as $discount) {
                            $discountAmount += $discount->getAmount();
                        }
                        echo $this->formatPrice($discountAmount);
                    ?>
        <?php endforeach; ?>

        <!-- OPTIONS -->
        <?php foreach($options as $option) : ?>
            <tr>
                <td>+ <?= $option->getName() ?> (option)
                <td class="currency"><?= $this->formatPrice($option->getGrossPrice()) ?>
                <td class="currency">
                    <?php
                    $discountAmount = 0;
                        foreach ($option->getDiscounts() as $discount) {
                            $discountAmount += $discount->getAmount();
                        }
                        echo $this->formatPrice($discountAmount);
                    ?>
         <?php endforeach; ?>


        <?php $bundle = $this->item->getSalesOrderItemBundle() ?>
        <?php if($bundle) : ?>
            <tr>
                <td colspan="4">
                    <?php if($this->item->getVariety() == 'Bundle') :?>
                        <div>
                            <a href="#" data-trigger-on-click="<?= htmlentities(json_encode([ 'target' => '#order-items-table__item-' . $this->itemIndex . ' .bundle-product-items-table', 'class' => 'hidden' ])); ?>">
                                <i class="icon-info-sign"></i> <?= __('Bundle Item Info') ?>
                            </a>
                            (<?= $bundle->getBundleType() ?>)
                            <br />
                            <?= $this->partial('Partials/bundle-item-info.phtml', array('bundleItems' => $bundle->getSalesOrderItemBundleItems())); ?>
                        </div>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endif; ?>
</table>
