<?php

/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace Spryker\Shared\Session;

interface SessionConstants
{

    const SESSION_HANDLER_COUCHBASE = 'couchbase';
    const SESSION_HANDLER_REDIS = 'redis';
    const SESSION_HANDLER_MYSQL = 'mysql';
    const SESSION_HANDLER_FILE = 'file';

    const SESSION_LIFETIME_1_HOUR = '3600';
    const SESSION_LIFETIME_30_DAYS = '2592000';
    const SESSION_LIFETIME_1_YEAR = '31536000';

    const SESSION_IS_TEST = 'SESSION_IS_TEST';

    const YVES_SESSION_REDIS_PROTOCOL = 'YVES_SESSION_REDIS_PROTOCOL';
    const YVES_SESSION_REDIS_PASSWORD = 'YVES_SESSION_REDIS_PASSWORD';
    const YVES_SESSION_REDIS_HOST = 'YVES_SESSION_REDIS_HOST';
    const YVES_SESSION_REDIS_PORT = 'YVES_SESSION_REDIS_PORT';
    const YVES_SESSION_REDIS_DATABASE = 'YVES_SESSION_REDIS_DATABASE';
    const YVES_SESSION_FILE_PATH = 'YVES_SESSION_FILE_PATH';
    const YVES_SESSION_PERSISTENT_CONNECTION = 'YVES_SESSION_PERSISTENT_CONNECTION';
    const YVES_SESSION_TIME_TO_LIVE = 'YVES_SESSION_TIME_TO_LIVE';

    const ZED_SESSION_REDIS_PROTOCOL = 'ZED_SESSION_REDIS_PROTOCOL';
    const ZED_SESSION_REDIS_HOST = 'ZED_SESSION_REDIS_HOST';
    const ZED_SESSION_REDIS_PORT = 'ZED_SESSION_REDIS_PORT';
    const ZED_SESSION_REDIS_PASSWORD = 'ZED_SESSION_REDIS_PASSWORD';
    const ZED_SESSION_REDIS_DATABASE = 'ZED_SESSION_REDIS_DATABASE';
    const ZED_SESSION_FILE_PATH = 'ZED_SESSION_FILE_PATH';
    const ZED_SESSION_PERSISTENT_CONNECTION = 'ZED_SESSION_PERSISTENT_CONNECTION';
    const ZED_SESSION_TIME_TO_LIVE = 'ZED_SESSION_TIME_TO_LIVE';
    const ZED_SESSION_COOKIE_NAME = 'ZED_SESSION_COOKIE_NAME';
    const ZED_SESSION_COOKIE_SECURE = 'ZED_COOKIE_SECURE';

}
