<?php

/**
 * (c) Spryker Systems GmbH copyright protected
 */

namespace Spryker\Shared\CustomerMailConnector;

interface CustomerMailConnectorConstants
{

    const MERGE_LANGUAGE_HANDLEBARS = 'MERGE_LANGUAGE_HANDLEBARS';

    const SHOP_MAIL_FROM_EMAIL_NAME = 'SHOP_MAIL_FROM_EMAIL_NAME';
    const SHOP_MAIL_PASSWORD_RESTORED_CONFIRMATION_SUBJECT = 'SHOP_MAIL_PASSWORD_RESTORED_CONFIRMATION_SUBJECT';
    const SHOP_MAIL_PASSWORD_RESTORED_CONFIRMATION_TOKEN = 'SHOP_MAIL_PASSWORD_RESTORED_CONFIRMATION_TOKEN';
    const SHOP_MAIL_PASSWORD_RESTORE_SUBJECT = 'SHOP_MAIL_PASSWORD_RESTORE_SUBJECT';
    const SHOP_MAIL_PASSWORD_RESTORE_TOKEN = 'SHOP_MAIL_PASSWORD_RESTORE_TOKEN';
    const SHOP_MAIL_REGISTRATION_SUBJECT = 'SHOP_MAIL_REGISTRATION_SUBJECT';
    const SHOP_MAIL_REGISTRATION_TOKEN = 'SHOP_MAIL_REGISTRATION_TOKEN';
    const SHOP_MAIL_FROM_EMAIL_ADDRESS = 'SHOP_MAIL_FROM_EMAIL_ADDRESS';

}
