<?php

/**
 * (c) Spryker Systems GmbH copyright protected
 */

namespace SprykerFeature\Shared\ProductImage;

use SprykerFeature\Shared\Library\ConfigInterface;

interface ProductImageConfig extends ConfigInterface
{

    const PRODUCT_IMAGE_ORIGINAL_PRODUCT_IMAGE_DIRECTORY = 'PRODUCT_IMAGE_ORIGINAL_PRODUCT_IMAGE_DIRECTORY';
    const PRODUCT_IMAGE_INCOMING_PRODUCT_IMAGE_DIRECTORY = 'PRODUCT_IMAGE_INCOMING_PRODUCT_IMAGE_DIRECTORY';
    const PRODUCT_IMAGE_PROCESSED_PRODUCT_IMAGE_DIRECTORY = 'PRODUCT_IMAGE_PROCESSED_PRODUCT_IMAGE_DIRECTORY';
    const PRODUCT_IMAGE_IMAGE_URL_PREFIX = 'PRODUCT_IMAGE_IMAGE_URL_PREFIX';
    const PRODUCT_IMAGE_AMAZON_S3_KEY = 'PRODUCT_IMAGE_AMAZON_S3_KEY';
    const PRODUCT_IMAGE_AMAZON_S3_SECRET = 'PRODUCT_IMAGE_AMAZON_S3_SECRET';
    const PRODUCT_IMAGE_AMAZON_S3_BUCKET_NAME = 'PRODUCT_IMAGE_AMAZON_S3_BUCKET_NAME';

}
