set	nocompatible	" must be the first line
syntax on           " color syntax
set expandtab       " ise softtabstop spaces instead of tab characters for indentation
set cindent
set softtabstop=2
set shiftwidth=2
filetype indent plugin on  " File type detection. Indent based on filetype
colorscheme	elflord
set laststatus=2
set statusline=%<%f\%h%m%r%=%-20.(line=%l\ \ col=%c%V\ \ totlin=%L%)\ \ \%h%m%r%=%-30(bytval=0x%B,%n%Y%)\%P