<?php

/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace Spryker\Shared\Storage;

interface StorageConstants
{

    const YVES_STORAGE_REDIS_PROTOCOL = 'YVES_STORAGE_REDIS_PROTOCOL';
    const YVES_STORAGE_REDIS_PASSWORD = 'YVES_STORAGE_REDIS_PASSWORD';
    const YVES_STORAGE_REDIS_HOST = 'YVES_STORAGE_REDIS_HOST';
    const YVES_STORAGE_REDIS_PORT = 'YVES_STORAGE_REDIS_PORT';
    const YVES_STORAGE_PERSISTENT_CONNECTION = 'YVES_STORAGE_PERSISTENT_CONNECTION';
    const YVES_STORAGE_REDIS_DATABASE = 'YVES_STORAGE_REDIS_DATABASE';

    const ZED_STORAGE_REDIS_PROTOCOL = 'ZED_STORAGE_REDIS_PROTOCOL';
    const ZED_STORAGE_REDIS_PASSWORD = 'ZED_STORAGE_REDIS_PASSWORD';
    const ZED_STORAGE_REDIS_HOST = 'ZED_STORAGE_REDIS_HOST';
    const ZED_STORAGE_REDIS_PORT = 'ZED_STORAGE_REDIS_PORT';
    const ZED_STORAGE_PERSISTENT_CONNECTION = 'ZED_STORAGE_PERSISTENT_CONNECTION';
    const ZED_STORAGE_REDIS_DATABASE = 'ZED_STORAGE_REDIS_DATABASE';

}
