<?php

/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerTest\Zed\FooBar\Business;

use Codeception\Test\Unit;

/**
 * Auto-generated group annotations
 * @group SprykerTest
 * @group Zed
 * @group FooBar
 * @group Business
 * @group Facade
 * @group FooBarFacadeTest
 * Add your own group annotations below this line
 */
class FooBarFacadeTest extends Unit
{
    /**
     * @var \SprykerTest\Zed\FooBar\FooBarBusinessTester
     */
    protected $tester;
    /**
     * @return void
     */
    public function testAddSomething_add_test_info(): void
    {
        $this->markTestIncomplete('This is an autogenerated test, please complete me.');
    }
}
