<?php

namespace SprykerFeature\Zed\ProductFrontendExporterConnector\Business\Builder;

use SprykerFeature\Shared\ProductFrontendExporterConnector\Code\KeyBuilder\SharedAbstractProductResourceKeyBuilder;

class AbstractProductResourceKeyBuilder extends SharedAbstractProductResourceKeyBuilder
{
}
