<?php  //[STAMP] 43a7de5c2649f52b9a11a3e6f25a82ec
namespace Kernel\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Kernel\Module\YvesUnit;

trait YvesUnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
