<?php  //[STAMP] edd99a4f5bed27b342d7bf5b55cd7a1e
namespace Kernel\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Kernel\Module\YvesUnit;

trait YvesUnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
