<?php  //[STAMP] 14b9e3bac3dca5155bf0c990e2729829
namespace Kernel\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Kernel\Module\YvesUnit;

trait YvesUnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
